### ISSUE TITLE
如何切换成CPU运行呢？

### ISSUE THREAD

**Issue by xiaoxuz** [justdark/pytorch-poetry-gen#1]

**Comment by justdark** [comment]
去掉 model.cuda() 就可以了

**Comment by xiaoxuz** [comment]
执行sample.py报错 请问是什么原因
Traceback (most recent call last):
  File "sample.py", line 40, in <module>
    print sample("春".decode('utf-8'))
  File "sample.py", line 31, in sample
    w = ix_to_word[topi]
KeyError: tensor(2914)

**Comment by czb2133** [comment]
> 执行sample.py报错 请问是什么原因
> Traceback (most recent call last):
> File "sample.py", line 40, in 
> print sample("春".decode('utf-8'))
> File "sample.py", line 31, in sample
> w = ix_to_word[topi]
> KeyError: tensor(2914)

作者的环境是python2，print还不用加括号，你用python3的话要加括号
